---
language: "python"
python:
- "3.6"
services:
- "docker"
# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------
before_script:
- "pip install invoke docker-compose"
- "curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > /tmp/get-poetry.py"
- "python /tmp/get-poetry.py -y"
- "source $HOME/.poetry/env"

script:
- "invoke build"
- "invoke tests"

# --------------------------------------------------------------------------
# Deploy
#  Uncomment the section below if you would like to publish a new release to pypi automatically
#  when a new tag is created in master. You"ll also need to generate a dedicated API key for this project in pypi
#  and encrypt the key with "travis encrypt PYPI_TOKEN=<value> --add env.global --com"
# --------------------------------------------------------------------------
# deploy:
#   provider: script
#   script: poetry config pypi-token.pypi $PYPI_TOKEN && poetry publish --build
#   skip_cleanup: true
#   on:
#     tags: true
#     branch: master
#     condition: $NAUTOBOT_VER = master
#     python: 3.7
