dev_addr: '127.0.0.1:8001'
edit_uri: edit/main/welcome_wizard/docs
site_name: Welcome Wizard Documentation
site_url: https://welcome_wizard.readthedocs.io/
repo_url: https://github.com/networktocode-llc/merlin
python:
  install:
    - requirements: docs/requirements.txt
theme:
  name: readthedocs
  navigation_depth: 4
  hljs_languages:
    - django
    - yaml
extra_css:
  - extra.css
markdown_extensions:
  - admonition
  - markdown_include.include:
      headingOffset: 1
  - toc:
      permalink: true
nav:
  - Introduction: 'index.md'
  - 'Import Wizard': 'import_wizard.md'
